from database import init_db, get_connection


SEED_INGREDIENTS = [
    {
        "name": "Sugar",
        "energy_kcal": 387.0,
        "protein_g": 0.0,
        "carbs_g": 100.0,
        "sugar_g": 100.0,
        "fat_g": 0.0,
        "saturated_fat_g": 0.0,
        "sodium_mg": 1.0,
    },
    {
        "name": "Salt",
        "energy_kcal": 0.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 0.0,
        "saturated_fat_g": 0.0,
        "sodium_mg": 38758.0,
    },
    {
        "name": "Butter",
        "energy_kcal": 717.0,
        "protein_g": 0.85,
        "carbs_g": 0.06,
        "sugar_g": 0.06,
        "fat_g": 81.11,
        "saturated_fat_g": 51.37,
        "sodium_mg": 11.0,
    },
    {
        "name": "Milk",
        "energy_kcal": 61.0,
        "protein_g": 3.15,
        "carbs_g": 4.8,
        "sugar_g": 5.05,
        "fat_g": 3.25,
        "saturated_fat_g": 1.86,
        "sodium_mg": 43.0,
    },
    {
        "name": "Whole wheat flour",
        "energy_kcal": 340.0,
        "protein_g": 13.2,
        "carbs_g": 72.0,
        "sugar_g": 0.4,
        "fat_g": 2.5,
        "saturated_fat_g": 0.43,
        "sodium_mg": 2.0,
    },
    {
        "name": "Maida",
        "energy_kcal": 364.0,
        "protein_g": 10.3,
        "carbs_g": 76.3,
        "sugar_g": 0.3,
        "fat_g": 1.0,
        "saturated_fat_g": 0.16,
        "sodium_mg": 2.0,
    },
    {
        "name": "Rice",
        "energy_kcal": 365.0,
        "protein_g": 7.1,
        "carbs_g": 80.0,
        "sugar_g": 0.1,
        "fat_g": 0.66,
        "saturated_fat_g": 0.18,
        "sodium_mg": 1.0,
    },
    {
        "name": "Olive oil",
        "energy_kcal": 884.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 100.0,
        "saturated_fat_g": 14.0,
        "sodium_mg": 2.0,
    },
    {
        "name": "Sunflower oil",
        "energy_kcal": 884.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 100.0,
        "saturated_fat_g": 10.3,
        "sodium_mg": 0.0,
    },
    {
        "name": "Peanut butter",
        "energy_kcal": 588.0,
        "protein_g": 25.0,
        "carbs_g": 20.0,
        "sugar_g": 9.2,
        "fat_g": 50.0,
        "saturated_fat_g": 10.0,
        "sodium_mg": 476.0,
    },
    {
        "name": "Egg",
        "energy_kcal": 143.0,
        "protein_g": 12.6,
        "carbs_g": 0.72,
        "sugar_g": 0.37,
        "fat_g": 9.5,
        "saturated_fat_g": 3.1,
        "sodium_mg": 142.0,
    },
    {
        "name": "Paneer",
        "energy_kcal": 265.0,
        "protein_g": 18.3,
        "carbs_g": 1.2,
        "sugar_g": 0.5,
        "fat_g": 20.8,
        "saturated_fat_g": 13.0,
        "sodium_mg": 22.0,
    },
    {
        "name": "Chicken breast",
        "energy_kcal": 165.0,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 3.6,
        "saturated_fat_g": 1.0,
        "sodium_mg": 74.0,
    },
    {
        "name": "Potato",
        "energy_kcal": 77.0,
        "protein_g": 2.0,
        "carbs_g": 17.0,
        "sugar_g": 0.8,
        "fat_g": 0.1,
        "saturated_fat_g": 0.03,
        "sodium_mg": 6.0,
    },
    {
        "name": "Onion",
        "energy_kcal": 40.0,
        "protein_g": 1.1,
        "carbs_g": 9.3,
        "sugar_g": 4.2,
        "fat_g": 0.1,
        "saturated_fat_g": 0.04,
        "sodium_mg": 4.0,
    },
    {
        "name": "Tomato",
        "energy_kcal": 18.0,
        "protein_g": 0.9,
        "carbs_g": 3.9,
        "sugar_g": 2.6,
        "fat_g": 0.2,
        "saturated_fat_g": 0.03,
        "sodium_mg": 5.0,
    },
    {
        "name": "Carrot",
        "energy_kcal": 41.0,
        "protein_g": 0.9,
        "carbs_g": 9.6,
        "sugar_g": 4.7,
        "fat_g": 0.2,
        "saturated_fat_g": 0.04,
        "sodium_mg": 69.0,
    },
    {
        "name": "Cabbage",
        "energy_kcal": 25.0,
        "protein_g": 1.3,
        "carbs_g": 5.8,
        "sugar_g": 3.2,
        "fat_g": 0.1,
        "saturated_fat_g": 0.02,
        "sodium_mg": 18.0,
    },
    {
        "name": "Green peas",
        "energy_kcal": 81.0,
        "protein_g": 5.4,
        "carbs_g": 14.5,
        "sugar_g": 5.7,
        "fat_g": 0.4,
        "saturated_fat_g": 0.07,
        "sodium_mg": 5.0,
    },
    {
        "name": "Chickpeas",
        "energy_kcal": 364.0,
        "protein_g": 19.3,
        "carbs_g": 60.7,
        "sugar_g": 10.7,
        "fat_g": 6.0,
        "saturated_fat_g": 0.6,
        "sodium_mg": 24.0,
    },
    {
        "name": "Lentils",
        "energy_kcal": 352.0,
        "protein_g": 24.6,
        "carbs_g": 63.4,
        "sugar_g": 2.0,
        "fat_g": 1.1,
        "saturated_fat_g": 0.2,
        "sodium_mg": 6.0,
    },
    {
        "name": "Moong dal",
        "energy_kcal": 347.0,
        "protein_g": 24.0,
        "carbs_g": 63.0,
        "sugar_g": 6.0,
        "fat_g": 1.2,
        "saturated_fat_g": 0.3,
        "sodium_mg": 15.0,
    },
    {
        "name": "Kidney beans",
        "energy_kcal": 333.0,
        "protein_g": 24.0,
        "carbs_g": 60.0,
        "sugar_g": 2.9,
        "fat_g": 0.8,
        "saturated_fat_g": 0.1,
        "sodium_mg": 24.0,
    },
    {
        "name": "Yogurt",
        "energy_kcal": 61.0,
        "protein_g": 3.5,
        "carbs_g": 4.7,
        "sugar_g": 4.7,
        "fat_g": 3.3,
        "saturated_fat_g": 2.1,
        "sodium_mg": 46.0,
    },
    {
        "name": "Ghee",
        "energy_kcal": 900.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 100.0,
        "saturated_fat_g": 62.0,
        "sodium_mg": 2.0,
    },
    {
        "name": "Banana",
        "energy_kcal": 89.0,
        "protein_g": 1.1,
        "carbs_g": 22.8,
        "sugar_g": 12.2,
        "fat_g": 0.3,
        "saturated_fat_g": 0.11,
        "sodium_mg": 1.0,
    },
    {
        "name": "Apple",
        "energy_kcal": 52.0,
        "protein_g": 0.3,
        "carbs_g": 13.8,
        "sugar_g": 10.4,
        "fat_g": 0.2,
        "saturated_fat_g": 0.03,
        "sodium_mg": 1.0,
    },
    {
        "name": "Almonds",
        "energy_kcal": 579.0,
        "protein_g": 21.2,
        "carbs_g": 21.6,
        "sugar_g": 4.4,
        "fat_g": 49.9,
        "saturated_fat_g": 3.8,
        "sodium_mg": 1.0,
    },
    {
        "name": "Cashews",
        "energy_kcal": 553.0,
        "protein_g": 18.2,
        "carbs_g": 30.2,
        "sugar_g": 5.9,
        "fat_g": 43.8,
        "saturated_fat_g": 7.8,
        "sodium_mg": 12.0,
    },
    {
        "name": "Jaggery",
        "energy_kcal": 383.0,
        "protein_g": 0.4,
        "carbs_g": 98.0,
        "sugar_g": 97.0,
        "fat_g": 0.1,
        "saturated_fat_g": 0.03,
        "sodium_mg": 27.0,
    },
    {
        "name": "Coconut milk",
        "energy_kcal": 230.0,
        "protein_g": 2.3,
        "carbs_g": 5.5,
        "sugar_g": 3.3,
        "fat_g": 23.8,
        "saturated_fat_g": 21.1,
        "sodium_mg": 15.0,
    },
    {
        "name": "Coconut oil",
        "energy_kcal": 892.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "sugar_g": 0.0,
        "fat_g": 100.0,
        "saturated_fat_g": 82.5,
        "sodium_mg": 0.0,
    },
    {
        "name": "Coriander leaves",
        "energy_kcal": 23.0,
        "protein_g": 2.1,
        "carbs_g": 3.7,
        "sugar_g": 0.9,
        "fat_g": 0.5,
        "saturated_fat_g": 0.01,
        "sodium_mg": 46.0,
    },
    {
        "name": "Spinach",
        "energy_kcal": 23.0,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "sugar_g": 0.4,
        "fat_g": 0.4,
        "saturated_fat_g": 0.06,
        "sodium_mg": 79.0,
    },
    {
        "name": "Garlic",
        "energy_kcal": 149.0,
        "protein_g": 6.4,
        "carbs_g": 33.1,
        "sugar_g": 1.0,
        "fat_g": 0.5,
        "saturated_fat_g": 0.09,
        "sodium_mg": 17.0,
    },
    {
        "name": "Ginger",
        "energy_kcal": 80.0,
        "protein_g": 1.8,
        "carbs_g": 17.8,
        "sugar_g": 1.7,
        "fat_g": 0.8,
        "saturated_fat_g": 0.2,
        "sodium_mg": 13.0,
    },
    {
        "name": "Oats",
        "energy_kcal": 389.0,
        "protein_g": 16.9,
        "carbs_g": 66.3,
        "sugar_g": 0.99,
        "fat_g": 6.9,
        "saturated_fat_g": 1.22,
        "sodium_mg": 2.0,
    },
    {
        "name": "Honey",
        "energy_kcal": 304.0,
        "protein_g": 0.3,
        "carbs_g": 82.4,
        "sugar_g": 82.1,
        "fat_g": 0.0,
        "saturated_fat_g": 0.0,
        "sodium_mg": 4.0,
    },
]


def seed_ingredients() -> int:
    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.executemany(
            """
            INSERT INTO ingredients (
                name,
                energy_kcal,
                protein_g,
                carbs_g,
                sugar_g,
                fat_g,
                saturated_fat_g,
                sodium_mg
            ) VALUES (
                :name,
                :energy_kcal,
                :protein_g,
                :carbs_g,
                :sugar_g,
                :fat_g,
                :saturated_fat_g,
                :sodium_mg
            )
            ON CONFLICT(name) DO UPDATE SET
                energy_kcal = excluded.energy_kcal,
                protein_g = excluded.protein_g,
                carbs_g = excluded.carbs_g,
                sugar_g = excluded.sugar_g,
                fat_g = excluded.fat_g,
                saturated_fat_g = excluded.saturated_fat_g,
                sodium_mg = excluded.sodium_mg
            """,
            SEED_INGREDIENTS,
        )
        connection.commit()
    return len(SEED_INGREDIENTS)


if __name__ == "__main__":
    init_db()
    count = seed_ingredients()
    print(f"Seeded {count} ingredients into nutrition.db")
